# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='answer',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
