# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161019_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='operation',
            name='operator',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], default='+', max_length=1),
        ),
    ]
