# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161019_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='answer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='num_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='num_2',
            field=models.FloatField(),
        ),
    ]
